### ISSUE TITLE
Kayo and AFL

### ISSUE THREAD

**Issue by hawksta** [xbmc-catchuptv-au/script.module.aussieaddonscommon#14]
Are you still doing Kayo and also will the AFL addon need updating before the season starts tomorrow...TIA

**Comment by glennguy** [comment]
No we don't do a Kayo add-on - check out the Matt Huisman/Slyguy Kayo add-on, it's great.

As per https://www.afl.com.au/news/545026/statement-telstra-delivers-giant-leap-forward-for-sports-streaming-with-kayo there will be no more live AFL matches in the add-on. The rest of the content like match replays, shows, highlights etc. will still be in the AFL add-on though.
